# Generated by Django 3.1.5 on 2021-01-10 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_hospital', '0003_auto_20210111_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(5, 0)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='weekdays',
            field=models.BooleanField(default=True),
        ),
    ]
