# Generated by Django 3.1.5 on 2021-01-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_hospital', '0005_auto_20210111_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='weekdays',
        ),
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.ManyToManyField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], to='form_hospital.Shift')),
            ],
        ),
    ]
